### ISSUE TITLE
Unable to require() Package

### ISSUE THREAD

**Issue by btleffler** [gillesdemey/cli-progress-bar#1]
I'm not able to load this package. It seems like [the `main` property of the package.json](https://github.com/gillesdemey/cli-progress-bar/blob/master/package.json#L5) isn't properly set.

Where it should be set to [`bar.js`](https://github.com/gillesdemey/cli-progress-bar/blob/master/bar.js), it's set to `index.js` which doesn't exit.

Thanks!

**Comment by gillesdemey** [comment]
Hey, thanks for the heads-up! I've published a fix on NPM.
